// 全ページ共通のヘッダーを組み立てる。
// <header class="site-header" data-site-header></header> があれば中身を差し込む。
// メニュー項目の追加はこの LINKS だけを編集すれば全ページに反映される。
// 文言は各ページが埋め込む window.LJ_I18N（locales/<lang>.json 由来）から取る。
// Vercel Web Analytics（Cookie 不使用の匿名集計）。全ページが読むこのファイルから読み込む。
(function () {
  const host = window.location.hostname;
  if (host === 'localhost' || host === '127.0.0.1') return;
  window.va = window.va || function () { (window.vaq = window.vaq || []).push(arguments); };
  const s = document.createElement('script');
  s.defer = true;
  s.src = '/_vercel/insights/script.js';
  document.head.appendChild(s);

  const ga = document.createElement('script');
  ga.src = '/js/analytics.js';
  document.head.appendChild(ga);
})();

(function () {
  const FALLBACK = {
    lang: 'ja',
    menu: {
      top: 'トップ', free: '無料診断', daily: '毎日の鑑定（プレミアム会員）', about: 'Libertas Jyotishとは',
      products: '鑑定書一覧', report: '生涯完全鑑定書',
      yearly: '年間運勢 鑑定書', compat: '相性 鑑定書', career: '仕事運・金運・天職 鑑定書', palm: 'カル・クンダリ（手相×出生図）',
      karma: 'Karma & Dharma ― 今世の天命',
      calendar: '年間運勢カレンダー', calendarNote: '準備中',
      mypage: '会員マイページ', legal: '特定商取引法・利用規約', contact: 'お問い合わせ',
      toggleLabel: 'メニュー', navLabel: 'サイトメニュー'
    }
  };
  /* MENU_I18N:start (generated by scripts/build-i18n.mjs) */
  const MENU_I18N = {"ar":{"top":"الرئيسية","free":"قراءة مجانية","daily":"القراءة اليومية (بريميوم)","about":"عن ليبرتاس جيوتيش","products":"قائمة التقارير","report":"Lifetime Report — تقرير العمر","yearly":"تقرير العام القادم","compat":"Compatibility Report — تقرير التوافق","career":"Career, Wealth & Calling Report — تقرير العمل والمال والرسالة","palm":"Kar-Kundali — Palm × Birth Chart · الكف × خريطة الميلاد","karma":"Karma & Dharma — Your Life Purpose · رسالة حياتك","calendar":"Annual Fortune Calendar — تقويم الحظ السنوي","calendarNote":"قريبًا","mypage":"صفحة العضوية","legal":"المعلومات القانونية والشروط","toggleLabel":"القائمة","navLabel":"قائمة الموقع","contact":"اتصل بنا"},"de":{"top":"Startseite","free":"Kostenlose Analyse","daily":"Tägliche Analyse (Premium)","about":"Über Libertas Jyotish","products":"Berichte","report":"Lifetime Report — Lebensbericht","yearly":"Jahresbericht","compat":"Compatibility Report — Kompatibilitätsbericht","career":"Career, Wealth & Calling Report — Bericht zu Beruf, Geld & Berufung","palm":"Kar-Kundali — Palm × Birth Chart · Handfläche × Geburtshoroskop","karma":"Karma & Dharma — Your Life Purpose · Ihre Lebensaufgabe","calendar":"Annual Fortune Calendar — Jährlicher Glückskalender","calendarNote":"bald verfügbar","mypage":"Mitgliederbereich","legal":"Impressum und AGB","toggleLabel":"Menü","navLabel":"Seitenmenü","contact":"Kontaktieren Sie uns"},"en":{"top":"Home","free":"Free reading","daily":"Daily reading (Premium)","about":"About Libertas Jyotish","products":"Reports","report":"Lifetime Report","yearly":"Year Ahead Report","compat":"Compatibility Report","career":"Career, Wealth & Calling Report","palm":"Kar-Kundali (Palm × Birth Chart)","karma":"Karma & Dharma — Your Life Purpose","calendar":"Annual Fortune Calendar","calendarNote":"coming soon","mypage":"Member page","legal":"Legal notice and terms","toggleLabel":"Menu","navLabel":"Site menu","contact":"Contact us"},"es":{"top":"Inicio","free":"Lectura gratuita","daily":"Lectura diaria (Premium)","about":"Sobre Libertas Jyotish","products":"Informes","report":"Lifetime Report — Informe Vitalicio","yearly":"Informe del año","compat":"Compatibility Report — Informe de compatibilidad","career":"Career, Wealth & Calling Report — Informe de carrera, dinero y vocación","palm":"Kar-Kundali — Palm × Birth Chart · palma × carta natal","karma":"Karma & Dharma — Your Life Purpose · tu propósito de vida","calendar":"Annual Fortune Calendar — Calendario Anual de la Fortuna","calendarNote":"próximamente","mypage":"Página de miembro","legal":"Información legal y términos","toggleLabel":"Menú","navLabel":"Menú del sitio","contact":"Contacto"},"fr":{"top":"Accueil","free":"Lecture gratuite","daily":"Lecture quotidienne (Premium)","about":"À propos de Libertas Jyotish","products":"Rapports","report":"Lifetime Report — Rapport à vie","yearly":"Rapport de l’année","compat":"Compatibility Report — Rapport de compatibilité","career":"Career, Wealth & Calling Report — Rapport carrière, argent et vocation","palm":"Kar-Kundali — Palm × Birth Chart · paume × thème natal","karma":"Karma & Dharma — Your Life Purpose · votre mission de vie","calendar":"Annual Fortune Calendar — Calendrier annuel de la destinée","calendarNote":"bientôt disponible","mypage":"Espace membre","legal":"Mentions légales et conditions","toggleLabel":"Menu","navLabel":"Menu du site","contact":"Nous contacter"},"id":{"top":"Beranda","free":"Pembacaan gratis","daily":"Pembacaan harian (Premium)","about":"Tentang Libertas Jyotish","products":"Daftar Laporan","report":"Lifetime Report — Laporan Seumur Hidup","yearly":"Laporan Tahun Depan","compat":"Compatibility Report — Laporan Kecocokan","career":"Career, Wealth & Calling Report — Laporan Karier, Keuangan & Panggilan Hidup","palm":"Kar-Kundali — Palm × Birth Chart · Telapak × Peta Kelahiran","karma":"Karma & Dharma — Your Life Purpose · Tujuan Hidup Anda","calendar":"Annual Fortune Calendar — Kalender Peruntungan Tahunan","calendarNote":"segera hadir","mypage":"Halaman anggota","legal":"Informasi hukum dan ketentuan","toggleLabel":"Menu","navLabel":"Menu situs","contact":"Hubungi kami"},"ja":{"top":"トップ","free":"無料診断","daily":"毎日の鑑定（プレミアム会員）","about":"Libertas Jyotishとは","products":"鑑定書一覧","report":"Lifetime Report — 生涯完全鑑定書","yearly":"年間運勢 鑑定書","compat":"Compatibility Report — 相性 鑑定書","career":"Career, Wealth & Calling Report — 仕事運・金運・天職 鑑定書","palm":"Kar-Kundali — Palm × Birth Chart · 手相×出生図","karma":"Karma & Dharma — Your Life Purpose · 今世の天命","calendar":"Annual Fortune Calendar — 年間運勢カレンダー","calendarNote":"準備中","mypage":"会員マイページ","legal":"特定商取引法・利用規約","toggleLabel":"メニュー","navLabel":"サイトメニュー","contact":"お問い合わせ"},"pt":{"top":"Início","free":"Leitura gratuita","daily":"Leitura diária (Premium)","about":"Sobre a Libertas Jyotish","products":"Relatórios","report":"Lifetime Report — Relatório Vitalício","yearly":"Relatório do ano","compat":"Compatibility Report — Relatório de compatibilidade","career":"Career, Wealth & Calling Report — Relatório de carreira, dinheiro e vocação","palm":"Kar-Kundali — Palm × Birth Chart · palma × mapa natal","karma":"Karma & Dharma — Your Life Purpose · seu propósito de vida","calendar":"Annual Fortune Calendar — Calendário Anual da Fortuna","calendarNote":"em breve","mypage":"Página de membro","legal":"Informações legais e termos","toggleLabel":"Menu","navLabel":"Menu do site","contact":"Contato"}};
  /* MENU_I18N:end */
  const i18n = window.LJ_I18N || FALLBACK;
  const lang = i18n.lang || FALLBACK.lang;
  const t = Object.assign({}, FALLBACK.menu, i18n.menu, MENU_I18N[lang] || MENU_I18N.en);
  const home = '/' + lang;
  // 解説記事がある言語では入門記事と記事一覧をメニューに出す。
  const guide = i18n.guide || null;
  // 単機能ツール（/<lang>/tools/...）を公開した言語ではメニューに出す。
  const tools = (i18n.tools && i18n.tools.items && i18n.tools.items.length) ? i18n.tools : null;

  const LINKS = [
    { href: home, label: t.top },
    { href: home + '#form-area', label: t.free },
    { href: home + '/mypage#premium', label: t.daily },
    // 鑑定書は見出し（/products 一覧）＋サブ項目。販売中はリンク、準備中は薄字＋注記。
    { divider: true },
    { href: home + '/products', label: t.products },
    { href: home + '/pdf-purchase', label: t.report, sub: true },
    { href: home + '/yearly', label: t.calendar, sub: true },
    { href: home + '/career', label: t.career, sub: true },
    { href: home + '/palm-chart', label: t.palm, sub: true },
    { href: home + '/compat', label: t.compat, sub: true },
    { href: home + '/karma', label: t.karma, sub: true }
  ];
  if (guide) {
    LINKS.push(
      { divider: true, label: guide.groupLabel },
      { href: guide.intro, label: guide.introLabel },
      { href: guide.hub, label: guide.hubLabel }
    );
  } else {
    LINKS.splice(3, 0, { href: home + '#about', label: t.about });
  }
  if (tools) {
    LINKS.push({ divider: true, label: tools.groupLabel });
    for (const tool of tools.items) LINKS.push({ href: tool.href, label: tool.label });
  }
  LINKS.push(
    { divider: true },
    { href: home + '/mypage', label: t.mypage },
    { href: home + '/legal', label: t.legal },
    { href: home + '/contact', label: t.contact }
  );

  function currentPath() {
    return window.location.pathname.replace(/\/$/, '') || home;
  }

  function render(header) {
    const path = currentPath();

    const logo = document.createElement('a');
    logo.className = 'lj-logo';
    logo.href = home;
    logo.innerHTML = '<img src="/img/libertas-logo.png" alt="Libertas Jyotish"><span>Libertas Jyotish</span>';

    const right = document.createElement('div');
    right.className = 'lj-header-right';

    const member = document.createElement('a');
    member.className = 'lj-btn-member';
    member.href = home + '/mypage';
    member.textContent = t.mypage;

    const toggle = document.createElement('button');
    toggle.type = 'button';
    toggle.className = 'lj-menu-toggle';
    toggle.setAttribute('aria-label', t.toggleLabel);
    toggle.setAttribute('aria-expanded', 'false');
    toggle.setAttribute('aria-controls', 'lj-menu');
    toggle.innerHTML = '<span></span><span></span><span></span>';

    right.appendChild(member);
    right.appendChild(toggle);

    const menu = document.createElement('nav');
    menu.id = 'lj-menu';
    menu.className = 'lj-menu';
    menu.hidden = true;
    menu.setAttribute('aria-label', t.navLabel);

    for (const item of LINKS) {
      if (item.divider) {
        const hr = document.createElement('div');
        hr.className = 'lj-menu-divider';
        menu.appendChild(hr);
        if (item.label) {
          const group = document.createElement('div');
          group.className = 'lj-menu-group';
          group.textContent = item.label;
          menu.appendChild(group);
        }
        continue;
      }
      const a = document.createElement(item.soon ? 'span' : 'a');
      if (item.soon) a.className = 'lj-menu-soon'; else a.href = item.href;
      if (item.sub) a.classList.add('lj-menu-sub');
      a.textContent = item.label;
      if (item.note) {
        const note = document.createElement('span');
        note.className = 'lj-menu-note';
        note.textContent = lang === 'ja' ? `（${item.note}）` : ` (${item.note})`;
        a.appendChild(note);
      }
      if (item.soon) { menu.appendChild(a); continue; }
      const target = item.href.split('#')[0].split('?')[0];
      const query = item.href.indexOf('?') >= 0 ? item.href.slice(item.href.indexOf('?')) : '';
      if ((target === path && (!query || query === window.location.search)) || (target !== home && path.indexOf(target + '/') === 0)) a.classList.add('is-current');
      menu.appendChild(a);
    }

    header.textContent = '';
    header.appendChild(logo);
    header.appendChild(right);
    document.body.appendChild(menu);

    function close() {
      menu.hidden = true;
      toggle.setAttribute('aria-expanded', 'false');
    }

    toggle.addEventListener('click', (e) => {
      e.stopPropagation();
      const open = menu.hidden;
      menu.hidden = !open;
      toggle.setAttribute('aria-expanded', String(open));
    });
    document.addEventListener('click', (e) => {
      if (!menu.hidden && !menu.contains(e.target)) close();
    });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') close();
    });
  }

  function init() {
    const header = document.querySelector('[data-site-header]');
    if (header) render(header);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
